PPWstory/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story6.urls')),
]

story6/urls.py
from .views import *
from django.shortcuts import render
from django.urls import path

app_name = 'story6'
urlpatterns = [
    path('', index, name='index'),
    path('add_status/', add_status, name='add_status')
]

story6/models.py
from django.db import models
import datetime

class Status(models.Model):
	status = models.CharField(max_length=300)
	date = models.DateTimeField(auto_now_add=True)

story6/forms.py
from django import forms
from .models import Status
from django.forms import ModelForm

class StatusForm(ModelForm):
    class Meta:
        model= Status
        fields = ['status']
        labels = {
            'status':'Status',
        }
        widgets = {
            'status' : forms.Textarea(attrs={'class': 'form-control',
                                        'type' : 'text', 'rows' : '3'}),
        }

story6/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import StatusForm
from .models import Status
# Create your views here.
def index(request):
	data = Status.objects.all()
	form = StatusForm(request.POST)
	context = {'form' : form, 'data' : data}
	return render(request, 'index.html', context)

def add_status(request):
	if request.method == 'POST':
		form = StatusForm(request.POST)
		if form.is_valid():
			form.save()
	return redirect('/')

story6/templates/index.html
{% load static from staticfiles%}


<!DOCTYPE html> 
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <title>{% block title %}{% endblock %}</title>

    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>




  </head>
  <body style="background-color: black">
    <!--content-->
    <div id="greet" style="display: block; text-align: center; margin-top: 3%; padding: 1%; background-color:blue; ">
      <h2 style="color: white;">HALO, APA KABAR?</h2>
    </div>
    <div class="form-container" style="padding:2% 15% 2%; color: white">
      <form method="POST" action="{% url 'story6:add_status' %}">
          {% csrf_token %}
          <div class="form-group">
            <label for="exampleFormControlTextarea1" >{{ form.status.label_tag }}</label>
            {{ form.status }}
          </div>
          <div class="form-group row">
            <div class="col-sm-10">
              <button type="submit" class="btn btn-primary" id="submit">Submit</button>
            </div>
          </div>
        </form>
        {% for db in data %}
               <small>{{ db.date }}</small>
               <p>{{ db.status }}</p>
               <hr style="border-top: 2px dashed white;">
        {% endfor %}
    </div>
  </body>
</html>